"""
sfpilot.summarizer - the Assessment as a small JSON state for Jev.
sfpilot.summarizer - 評価を Jev 向けの小さな JSON state にする。

Two rules shape this module, both from the design's constraint table:

  1. **No numbers.** Every value is one of a fixed set of words. If a
     number reached Jev it would invite exactly the comparison the model
     cannot do reliably. `assert_no_numbers()` enforces this and is
     exercised by the tests.
  2. **Keep it small.** Irrelevant state lowers accuracy (documented
     under `model-jaggedness/jev-1.13`), so a field whose value is
     unknown is omitted rather than sent as "unknown".

本モジュールを決めているのは、設計の制約表から来る 2 つの規則:

  1. **数値を載せない。** すべての値はあらかじめ決めた語のいずれか。数値が
     Jev に届くと、モデルが確実には行えない比較を誘発してしまう。
     `assert_no_numbers()` がこれを機械的に守り、試験でも確認する。
  2. **小さく保つ。** 無関係な state は精度を下げる（`model-jaggedness/jev-1.13`）。
     値が不明な項目は「不明」として送らず、項目ごと省く。

Why the state is written in English: the model's documented accuracy is
highest in English, and these words are generated by code, never read by
the operator. The one exception is `operator_instruction`, which is the
operator's own sentence and is passed through unchanged -- translating it
would be this layer inventing meaning.

state を英語で書く理由: モデルの精度は英語で最も高く、ここの語はコードが
生成するもので操作者が読むものではない。唯一の例外は `operator_instruction` で、
これは操作者自身の文であり、そのまま渡す — 訳せばこの層が意味を作ることになる。
"""

from .monitor import Assessment

# Japanese classification -> the English word sent to Jev. One table, so
# the vocabulary Jev sees is enumerable and reviewable in one place.
# 日本語の区分 -> Jev に送る英語の語。語彙を 1 か所で一覧・点検できるよう
# テーブルにまとめる。
_WORDS = {
    # altitude / 高度
    "目標どおり": "on target",
    "目標より高い": "above target",
    "目標より低い": "below target",
    # altitude trend / 高度の傾向
    "安定": "steady",
    "上昇中": "climbing",
    "下降中": "sinking",
    # horizontal drift / 水平の流れ
    "ほぼ静止": "almost stationary",
    "前へゆっくり流されている": "drifting slowly forward",
    "後ろへゆっくり流されている": "drifting slowly backward",
    "右へゆっくり流されている": "drifting slowly to the right",
    "左へゆっくり流されている": "drifting slowly to the left",
    "前へ速く流されている": "drifting fast forward",
    "後ろへ速く流されている": "drifting fast backward",
    "右へ速く流されている": "drifting fast to the right",
    "左へ速く流されている": "drifting fast to the left",
    # attitude / 姿勢
    "水平に近い": "close to level",
    "やや傾いている": "slightly tilted",
    "大きく傾いている": "steeply tilted",
    # position estimate / 位置推定
    "信頼できる": "reliable",
    "発散している": "diverged",
    # ground distance sensor / 対地距離センサ
    "正常": "working normally",
    "当てにならない値": "reading is not trustworthy",
    # forward clearance / 前方の空き
    #
    # "cannot be measured" is carried to Jev rather than dropped, unlike the
    # "不明" that means a field was never populated. The two are different
    # facts: one says nobody looked, the other says the sensor looked and
    # could not tell -- and the second is a reason for caution, not silence.
    # 「測定不能」は、項目が埋まらなかったことを表す「不明」と違い、省かずに Jev へ
    # 渡す。両者は別の事実である: 一方は「誰も見ていない」、他方は「センサが見て、
    # 判別できなかった」であり、後者は沈黙ではなく警戒の理由である。
    "開けている": "open",
    "やや近い": "somewhat near",
    "壁が近い": "wall near",
    "測定不能": "cannot be measured",
    # battery level / 電池残量
    "十分": "plenty left",
    "残り少ない": "running low",
    "危険": "dangerously low",
    # battery trend / 電池の傾向
    "ゆるやかに低下": "falling gradually",
    "急に低下": "fell sharply in the last few seconds",
    # flight phase / 飛行段階
    "飛行中": "flying",
    "不明": "unknown",
}


def _word(japanese: str) -> str:
    """Translate one classification, falling back to the input.
    区分を 1 つ訳す。表に無ければ入力をそのまま返す。"""
    return _WORDS.get(japanese, japanese)


def forward_word(japanese: str) -> str:
    """Translate one forward-clearance classification for Jev.

    Exposed because `explore.py` classifies EIGHT bearings with the same
    `monitor.FORWARD_*` words and has to put all eight in the state. It
    goes through this table rather than keeping its own, so a wall reads as
    the same word whether it is in front of the craft or off to one side --
    a second table would be the way the two come to disagree, which is the
    failure the battery-trend names were made constants to prevent.

    前方の空きの区分を 1 つ、Jev 向けに訳す。

    公開するのは、`explore.py` が同じ `monitor.FORWARD_*` の語で **8 方位**を
    区分し、その 8 つすべてを state に載せるためである。独自の表を持たずここを
    通すので、壁は、機体の正面にあろうと横にあろうと同じ語として読める。表が
    2 つあることこそ両者が食い違う経路であり、電池の傾向の区分名を定数にして
    防いだのと同じ失敗である。
    """
    return _word(japanese)


def summarize(
    assessment: Assessment,
    mission: dict = None,
    operator_instruction: str = None,
    surroundings: dict = None,
) -> dict:
    """Build the state object sent to Jev.

    Fields whose value is unknown are left out entirely (rule 2 above).
    Jev へ送る state を組み立てる。値が不明な項目は丸ごと省く（上記の規則 2）。

    `surroundings` is the eight-bearing sweep (`explore.surroundings_state`)
    and is absent unless one has been taken. It is passed in rather than
    derived from the assessment because a sweep is a MEASUREMENT the craft
    went and made, not a classification of the present sample: the Monitor
    sees only where the sensor points now.

    `surroundings` は 8 方位の掃引（`explore.surroundings_state`）であり、掃引を
    取っていない限り載らない。評価から導かず引数で受け取るのは、掃引が「機体が
    出かけて行って取ってきた**測定**」であって、今このサンプルの区分ではない
    からである。Monitor に見えるのは、センサが今向いている先だけである。
    """
    flight = {}
    _put(flight, "phase", assessment.phase)
    _put(flight, "altitude", assessment.altitude)
    _put(flight, "altitude_trend", assessment.altitude_trend)
    _put(flight, "horizontal_drift", assessment.horizontal_drift)
    _put(flight, "attitude", assessment.attitude)
    _put(flight, "position_estimate", assessment.position_estimate)
    _put(flight, "ground_distance_sensor", assessment.ground_distance_sensor)
    _put(flight, "forward_clearance", assessment.forward_clearance)

    battery = {}
    _put(battery, "level", assessment.battery_level)
    _put(battery, "trend", assessment.battery_trend)

    state = {"flight": flight}
    if battery:
        state["battery"] = battery
    if surroundings:
        state["surroundings"] = surroundings
    if mission:
        state["mission"] = mission
    if assessment.recent_events:
        state["recent_events"] = list(assessment.recent_events)
    if operator_instruction:
        # Passed through verbatim: it is the operator's own sentence.
        # 操作者自身の文なのでそのまま渡す。
        state["operator_instruction"] = operator_instruction
    return state


def _put(target: dict, key: str, japanese: str) -> None:
    """Add a translated field, unless its value is unknown.
    訳した項目を追加する。値が不明なら追加しない。"""
    is_unknown = japanese in ("", "不明", None)
    if is_unknown:
        return
    target[key] = _word(japanese)


def signature(state: dict) -> str:
    """A stable fingerprint of the situation's classification.

    The Arbiter compares the signature taken when a question was asked
    with the signature at the moment the answer arrives: if they differ,
    the situation moved on and the answer describes a world that no
    longer exists. Because the state holds only words, any change in the
    signature is a genuine change of category, not sensor jitter.

    状況の区分の指紋。

    Arbiter は質問時の指紋と応答到着時の指紋を照合し、異なれば「状況が
    変わった」と判断して答えを破棄する。state は言葉しか持たないため、
    指紋の変化はセンサの揺らぎではなく区分そのものの変化を意味する。

    `recent_events` and `mission.elapsed` are excluded: they change
    constantly without the situation changing, and would make every
    answer look stale.
    `recent_events` と `mission.elapsed` は除外する。状況が変わらなくても
    絶えず変化し、すべての答えが鮮度切れに見えてしまうため。

    `surroundings.measured` is excluded for exactly the reason
    `mission.elapsed` is: it is the age of the sweep, so it moves on its
    own as time passes while the bearings it describes stay put. The
    BEARINGS are included, because a bearing changing from open to wall
    near is precisely the kind of change an answer in flight should be
    discarded for.
    `surroundings.measured` は `mission.elapsed` とまったく同じ理由で除外する。
    掃引の古さなので、記述している方位が動かないまま、時間の経過だけで勝手に
    変わる。**方位そのもの**は含める。ある方位が「開けている」から「壁が近い」へ
    変わることは、往復中の答えを破棄すべき変化そのものだからである。
    """
    parts = []
    for section in ("flight", "battery"):
        values = state.get(section) or {}
        for key in sorted(values):
            parts.append(f"{section}.{key}={values[key]}")
    surroundings = state.get("surroundings") or {}
    for key in sorted(surroundings):
        if key == "measured":
            continue
        parts.append(f"surroundings.{key}={surroundings[key]}")
    mission = state.get("mission") or {}
    for key in sorted(mission):
        if key == "elapsed":
            continue
        parts.append(f"mission.{key}={mission[key]}")
    if "operator_instruction" in state:
        parts.append(f"instruction={state['operator_instruction']}")
    return "|".join(parts)


def assert_no_numbers(state: dict) -> None:
    """Raise if any value in the state is a number.

    This is the design's first constraint made mechanical. It runs before
    every request in JevJudge, so a future field that forgets to classify
    its value fails loudly here instead of quietly degrading the model's
    answers.
    state のどこかに数値があれば例外を出す。

    設計の第一の制約を機械的に守るための検査。JevJudge が毎リクエスト前に
    実行するので、将来追加した項目が区分し忘れた数値を持っていれば、答えの
    質が静かに下がるのではなく、ここではっきり失敗する。
    """
    _walk_for_numbers(state, "state")


def _walk_for_numbers(node, path: str) -> None:
    is_number = isinstance(node, (int, float)) and not isinstance(node, bool)
    if is_number:
        raise ValueError(
            f"{path}: numeric value {node!r} must not be sent to Jev — classify it "
            f"in monitor.py first（数値は Jev に渡さない。monitor.py で区分すること）"
        )
    if isinstance(node, dict):
        for key, value in node.items():
            _walk_for_numbers(value, f"{path}.{key}")
        return
    if isinstance(node, (list, tuple)):
        for index, value in enumerate(node):
            _walk_for_numbers(value, f"{path}[{index}]")
